title: UNI2 Character Playbooks
description: A collection of different strategies for your favorite characters
theme: just-the-docs


url: https://just-the-docs.github.io

aux_links:
  UNI2 Wiki: https://mizuumi.wiki/w/Under_Night_In-Birth/UNI2

exclude:
  - README.md
  - LICENSE.md
  - _config.yml
  - _data/aux_links.yml
  - docs/template.md

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

sass:
  sass_dir: _sass
  quiet_deps: true
  silence_deprecations: ['import']